@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")
Container(postService, "Post service", "Software system", "CRUD for posts, comments and likes")
Container(relationService, "Relation service", "Software system", "Stores relation info")
Container(mediaService, "Media service", "Software system", "Stores media files")
Container(pointService, "Point service", "Software system", "Stores GEO data")
Container(feedService, "Feed service", "Software system", "Work with cached feed")

Rel(user, mediaService, "Upload or download")
Rel(user, pointService, "Get points or save point")
Rel(user, postService, "CRUD")
Rel(user, relationService, "Subscribe or unsubscribe")
Rel(user, feedService, "Get feed")
@enduml